services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - django_docker_net
  db:
    image: postgres:16.1
    restart: always
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - db.env
    networks:
      - django_docker_net
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./custom-nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web



networks:
  django_docker_net:
    driver: bridge

volumes:
    db-data:

